version: "3.9"
services:
  api:
    image: recipes-api
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
      - MONGO_DATABASE=demo
      - REDIS_URI=redis:6379
    networks:
      - api_network
    external_links:
      - mongodb
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - api_network
  mongodb:
    image: mongo:4.4.3
    networks:
      - api_network
    ports:
      - 27017:27017
    volumes:
      - $PWD/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - api_network
networks:
  api_network: